export type FileDataType = {
    id: number,
    createdOn: string,
    updatedOn?: string,
    createdByName: string,
    createdByUsername: string,
    createdBy: number,
    updatedBy?: number,
    title: string,
    size: string,
    sizeBytes?: number| null,
    mimeType?: string| null,
    location?: string| null,
    extension?: string| null,
    currentVersion?: number| null,
    content?: string|null,
    shared?: boolean|null,
    shareType?: string|null,
    archived: boolean,
    archivalOn?: string|null,
    archival: boolean,
    name: string,
    version?: number| null,
    favourite?: boolean|null,
    description?: string|null,
    folder?: boolean|null,
    updatedByName?: string,
    updatedByUsername?: string,
    updatedOnDetail?: string,
}